# -----------------------------------------------------------------------------
# pnpm-workspace.yaml - PNPM Workspace Configuration
# -----------------------------------------------------------------------------
# This file defines the structure and configuration of a PNPM workspace.
# It includes package inclusion/exclusion patterns and workspace catalogs.
#
# Documentation:
# - PNPM Workspaces: https://pnpm.io/workspaces
# - PNPM Configuration Options: https://pnpm.io/npmrc
# -----------------------------------------------------------------------------

packages:
  - "!**/test/**"
  - "!**/__tests__/**"
  - "example"
  - "packages/**"

catalogs:
  workspace:
    "@commitlint/cli": "^19.5.0"
    "@commitlint/config-conventional": "^19.5.0"
    "@cspell/cspell-types": "^8.16.0"
    "@emotion/react": "^11.13.3"
    "@floating-ui/dom": "^1.6.12"
    "@material-tailwind/react": "^2.1.10"
    "@nabla/vite-plugin-eslint": "^2.0.4"
    "@pnpm/read-package-json": "^9.0.9"
    "@pnpm/types": "^12.2.0"
    "@rollup/plugin-commonjs": "^28.0.1"
    "@rollup/plugin-node-resolve": "^15.3.0"
    "@rollup/plugin-typescript": "^12.1.1"
    "@storybook/addon-coverage": "^1.0.4"
    "@storybook/addon-essentials": "^8.4.4"
    "@storybook/addon-interactions": "^8.4.4"
    "@storybook/addon-links": "^8.4.4"
    "@storybook/addon-onboarding": "^8.4.4"
    "@storybook/addon-themes": "^8.4.4"
    "@storybook/blocks": "^8.4.4"
    "@storybook/manager-api": "^8.4.4"
    "@storybook/react-vite": "^8.4.4"
    "@storybook/react": "^8.4.4"
    "@storybook/test": "^8.4.4"
    "@storybook/theming": "^8.4.4"
    "@tailwindcss/forms": "^0.5.9"
    "@testing-library/react": "^16.0.1"
    "@types/jest": "^29.5.14"
    "@types/lodash": "^4.17.13"
    "@types/node": "^22.9.0"
    "@types/react-dom": "^18.3.1"
    "@types/react": "^18.3.12"
    "@typescript-eslint/eslint-plugin": "^8.15.0"
    "@typescript-eslint/parser": "^8.15.0"
    "@vitejs/plugin-react-swc": "^3.7.1"
    "@vitejs/plugin-react": "^4.3.3"
    "asdf": "^1.2.3"
    "autoprefixer": "^10.4.20"
    "camelcase": "^8.0.0"
    "change-case": "^5.4.4"
    "commitizen": "^4.3.1"
    "cross-env": "^7.0.3"
    "cspell": "^8.16.0"
    "cz-conventional-changelog": "^3.3.0"
    "dotenv-cli": "^7.4.2"
    "eslint-config-prettier": "^9.1.0"
    "eslint-plugin-react": "^7.37.2"
    "eslint-plugin-storybook": "^0.11.0"
    "eslint": "^9.15.0"
    "husky": "^9.1.7"
    "jest": "^29.7.0"
    "lerna": "^8.1.9"
    "lint-staged": "^15.2.10"
    "lodash": "^4.17.21"
    "mega-linter-runner": "^8.2.0"
    "msw-storybook-addon": "^2.0.4"
    "msw": "^2.6.5"
    "nx": "^20.1.2"
    "pnpm": "^9.14.1"
    "postcss-cli": "^11.0.0"
    "postcss": "^8.4.49"
    "prettier-plugin-pkg": "^0.18.1"
    "prettier-plugin-sh": "^0.14.0"
    "prettier": "^3.3.3"
    "prop-types": "^15.8.1"
    "react-dom": "^18.3.1"
    "react-helmet-async": "^2.0.5"
    "react-router-dom": "^6.28.0"
    "react-virtuoso": "^4.12.0"
    "react": "^18.3.1"
    "rollup-plugin-peer-deps-external": "^2.2.4"
    "rollup-plugin-postcss": "^4.0.2"
    "rollup": "^4.27.3"
    "storybook": "^8.4.4"
    "stylelint-prettier": "^5.0.2"
    "stylelint": "^16.10.0"
    "syncpack": "^13.0.0"
    "tailwind-config-viewer": "^2.0.4"
    "tailwindcss": "^3.4.15"
    "turbo": "^2.3.1"
    "ts-node": "^10.9.2"
    "tslib": "^2.8.1"
    "type-fest": "^4.27.0"
    "typescript": "^5.6.3"
    "vite-plugin-dts": "^4.3.0"
    "vite-plugin-pwa": "^0.21.0"
    "vite-tsconfig-paths": "^5.1.3"
    "vite": "^5.4.11"
    "vitest": "^2.1.5"
    "madge": "^8.0.0"
    "@emotion/cache": "^11.13.5"
    "patch-package": "^8.0.0"
    "@babel/runtime": "^7.26.0"
    "@emotion/weak-memoize": "^0.4.0"
    "hoist-non-react-statics": "^3.3.2"
    "@emotion/utils": "^1.4.2"
    "@emotion/serialize": "^1.3.3"
    "typedoc": "^0.26.11"
    "scheduler": "^0.23.2"
