# ======================================================================
#  docker-compose-local.yml
#  Additional local services for the dev environment.
#  Run them inside the container using docker-in-docker.
# ======================================================================
services:
  plantuml:
    image: plantuml/plantuml-server:latest
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
